IF %BGT_VAR%
Global("TICamryn","GLOBAL",0)
Global("TICBOOK13_Gone","AR0126",0)  //you need a check variable, or the script block will be true always and block everything beneath it

THEN
RESPONSE #100
ActionOverride("Container1",DestroyItem("TICBOOK13")) //unfortunately, you need the container name, yes. And don't get discouraged if it seem not to work the first time
SetGlobal("TICBOOK13_Gone","AR0126",1)
Continue()
END