IF %BGT_VAR%
Global("TICamryn","GLOBAL",0)
Global("TICBOOK09_Gone","AR4804",0)  //you need a check variable, or the script block will be true always and block everything beneath it

THEN
RESPONSE #100
ActionOverride("Container2",DestroyItem("TICBOOK09")) //unfortunately, you need the container name, yes. And don't get discouraged if it seem not to work the first time
SetGlobal("TICBOOK09_Gone","AR4804",1)
Continue()
END